#!/bin/sh
#
# Copyright (c) <2015> <cetc 32> and others.  All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the Eclipse Public License
# v1.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
# @author cetc 32
# @version 0.1
#

#getent group cetc >/dev/null || groupadd -r cetc
#getent passwd cetc >/dev/null || \
#useradd -d /usr/share/anti-ddos -g cetc -M -r cetc

if [ -f /opt/antiddos/install/uninstall.sh ];then
   echo -n "Removing old anti ddos..."
   sh /opt/antiddos/install/uninstall.sh
   echo "done"
fi

exit 0
